sonar.projectKey=https://sonarcloud.io/api/project_badges/measure?project=unlaudd_go-project-244&metric=alert_status
sonar.organization=Denis Lysenko
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.python.coverage.reportPaths=coverage.out
