# SonarCloud configuration for Go project
sonar.projectKey=unlaudd_go-project-244
sonar.organization=Denis Lysenko

# Исходный код
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,**/vendor/**,**/bin/**

# Тесты
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Покрытие кода (Go)
sonar.go.coverage.reportPaths=coverage.out

# Кодировка
sonar.sourceEncoding=UTF-8